/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SoulRouteImport } from './routes/soul'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PillarsRouteImport } from './routes/pillars'
import { Route as OneWordStartRouteImport } from './routes/one-word-start'
import { Route as ManifestoFullRouteImport } from './routes/manifesto-full'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as KnowledgeBeforeActionRouteImport } from './routes/knowledge-before-action'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GlobalRouteImport } from './routes/global'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as FoundationRouteImport } from './routes/foundation'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as BookRouteImport } from './routes/book'
import { Route as AppreciationRouteImport } from './routes/appreciation'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PillarsSlugRouteImport } from './routes/pillars.$slug'
import { Route as JourneyStartRouteImport } from './routes/journey.start'
import { Route as JourneySafetyRouteImport } from './routes/journey.safety'
import { Route as JourneyReviewRouteImport } from './routes/journey.review'
import { Route as JourneyReflectionRouteImport } from './routes/journey.reflection'
import { Route as JourneyPrivacyRouteImport } from './routes/journey.privacy'
import { Route as JourneyPreferencesRouteImport } from './routes/journey.preferences'
import { Route as JourneyOrientationRouteImport } from './routes/journey.orientation'
import { Route as JourneyMilestoneRouteImport } from './routes/journey.milestone'
import { Route as JourneyConfirmRouteImport } from './routes/journey.confirm'
import { Route as JourneyCompleteRouteImport } from './routes/journey.complete'
import { Route as JourneyAccessibilityRouteImport } from './routes/journey.accessibility'
import { Route as JourneyQuestQuestIdRouteImport } from './routes/journey.quest.$questId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulRoute = SoulRouteImport.update({
  id: '/soul',
  path: '/soul',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarsRoute = PillarsRouteImport.update({
  id: '/pillars',
  path: '/pillars',
  getParentRoute: () => rootRouteImport,
} as any)
const OneWordStartRoute = OneWordStartRouteImport.update({
  id: '/one-word-start',
  path: '/one-word-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoFullRoute = ManifestoFullRouteImport.update({
  id: '/manifesto-full',
  path: '/manifesto-full',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBeforeActionRoute = KnowledgeBeforeActionRouteImport.update({
  id: '/knowledge-before-action',
  path: '/knowledge-before-action',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalRoute = GlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationRoute = FoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppreciationRoute = AppreciationRouteImport.update({
  id: '/appreciation',
  path: '/appreciation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarsSlugRoute = PillarsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PillarsRoute,
} as any)
const JourneyStartRoute = JourneyStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneySafetyRoute = JourneySafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyReviewRoute = JourneyReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyReflectionRoute = JourneyReflectionRouteImport.update({
  id: '/reflection',
  path: '/reflection',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyPrivacyRoute = JourneyPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyPreferencesRoute = JourneyPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyOrientationRoute = JourneyOrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyMilestoneRoute = JourneyMilestoneRouteImport.update({
  id: '/milestone',
  path: '/milestone',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyConfirmRoute = JourneyConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyCompleteRoute = JourneyCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyAccessibilityRoute = JourneyAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyQuestQuestIdRoute = JourneyQuestQuestIdRouteImport.update({
  id: '/quest/$questId',
  path: '/quest/$questId',
  getParentRoute: () => JourneyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/appreciation': typeof AppreciationRoute
  '/book': typeof BookRoute
  '/consent': typeof ConsentRoute
  '/domains': typeof DomainsRoute
  '/ecosystem': typeof EcosystemRoute
  '/foundation': typeof FoundationRoute
  '/founder': typeof FounderRoute
  '/global': typeof GlobalRoute
  '/join': typeof JoinRoute
  '/journey': typeof JourneyRouteWithChildren
  '/knowledge-before-action': typeof KnowledgeBeforeActionRoute
  '/manifesto': typeof ManifestoRoute
  '/manifesto-full': typeof ManifestoFullRoute
  '/one-word-start': typeof OneWordStartRoute
  '/pillars': typeof PillarsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/soul': typeof SoulRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/journey/accessibility': typeof JourneyAccessibilityRoute
  '/journey/complete': typeof JourneyCompleteRoute
  '/journey/confirm': typeof JourneyConfirmRoute
  '/journey/milestone': typeof JourneyMilestoneRoute
  '/journey/orientation': typeof JourneyOrientationRoute
  '/journey/preferences': typeof JourneyPreferencesRoute
  '/journey/privacy': typeof JourneyPrivacyRoute
  '/journey/reflection': typeof JourneyReflectionRoute
  '/journey/review': typeof JourneyReviewRoute
  '/journey/safety': typeof JourneySafetyRoute
  '/journey/start': typeof JourneyStartRoute
  '/pillars/$slug': typeof PillarsSlugRoute
  '/journey/quest/$questId': typeof JourneyQuestQuestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/appreciation': typeof AppreciationRoute
  '/book': typeof BookRoute
  '/consent': typeof ConsentRoute
  '/domains': typeof DomainsRoute
  '/ecosystem': typeof EcosystemRoute
  '/foundation': typeof FoundationRoute
  '/founder': typeof FounderRoute
  '/global': typeof GlobalRoute
  '/join': typeof JoinRoute
  '/journey': typeof JourneyRouteWithChildren
  '/knowledge-before-action': typeof KnowledgeBeforeActionRoute
  '/manifesto': typeof ManifestoRoute
  '/manifesto-full': typeof ManifestoFullRoute
  '/one-word-start': typeof OneWordStartRoute
  '/pillars': typeof PillarsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/soul': typeof SoulRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/journey/accessibility': typeof JourneyAccessibilityRoute
  '/journey/complete': typeof JourneyCompleteRoute
  '/journey/confirm': typeof JourneyConfirmRoute
  '/journey/milestone': typeof JourneyMilestoneRoute
  '/journey/orientation': typeof JourneyOrientationRoute
  '/journey/preferences': typeof JourneyPreferencesRoute
  '/journey/privacy': typeof JourneyPrivacyRoute
  '/journey/reflection': typeof JourneyReflectionRoute
  '/journey/review': typeof JourneyReviewRoute
  '/journey/safety': typeof JourneySafetyRoute
  '/journey/start': typeof JourneyStartRoute
  '/pillars/$slug': typeof PillarsSlugRoute
  '/journey/quest/$questId': typeof JourneyQuestQuestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/appreciation': typeof AppreciationRoute
  '/book': typeof BookRoute
  '/consent': typeof ConsentRoute
  '/domains': typeof DomainsRoute
  '/ecosystem': typeof EcosystemRoute
  '/foundation': typeof FoundationRoute
  '/founder': typeof FounderRoute
  '/global': typeof GlobalRoute
  '/join': typeof JoinRoute
  '/journey': typeof JourneyRouteWithChildren
  '/knowledge-before-action': typeof KnowledgeBeforeActionRoute
  '/manifesto': typeof ManifestoRoute
  '/manifesto-full': typeof ManifestoFullRoute
  '/one-word-start': typeof OneWordStartRoute
  '/pillars': typeof PillarsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/soul': typeof SoulRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/journey/accessibility': typeof JourneyAccessibilityRoute
  '/journey/complete': typeof JourneyCompleteRoute
  '/journey/confirm': typeof JourneyConfirmRoute
  '/journey/milestone': typeof JourneyMilestoneRoute
  '/journey/orientation': typeof JourneyOrientationRoute
  '/journey/preferences': typeof JourneyPreferencesRoute
  '/journey/privacy': typeof JourneyPrivacyRoute
  '/journey/reflection': typeof JourneyReflectionRoute
  '/journey/review': typeof JourneyReviewRoute
  '/journey/safety': typeof JourneySafetyRoute
  '/journey/start': typeof JourneyStartRoute
  '/pillars/$slug': typeof PillarsSlugRoute
  '/journey/quest/$questId': typeof JourneyQuestQuestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/appreciation'
    | '/book'
    | '/consent'
    | '/domains'
    | '/ecosystem'
    | '/foundation'
    | '/founder'
    | '/global'
    | '/join'
    | '/journey'
    | '/knowledge-before-action'
    | '/manifesto'
    | '/manifesto-full'
    | '/one-word-start'
    | '/pillars'
    | '/privacy'
    | '/soul'
    | '/status'
    | '/terms'
    | '/journey/accessibility'
    | '/journey/complete'
    | '/journey/confirm'
    | '/journey/milestone'
    | '/journey/orientation'
    | '/journey/preferences'
    | '/journey/privacy'
    | '/journey/reflection'
    | '/journey/review'
    | '/journey/safety'
    | '/journey/start'
    | '/pillars/$slug'
    | '/journey/quest/$questId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/appreciation'
    | '/book'
    | '/consent'
    | '/domains'
    | '/ecosystem'
    | '/foundation'
    | '/founder'
    | '/global'
    | '/join'
    | '/journey'
    | '/knowledge-before-action'
    | '/manifesto'
    | '/manifesto-full'
    | '/one-word-start'
    | '/pillars'
    | '/privacy'
    | '/soul'
    | '/status'
    | '/terms'
    | '/journey/accessibility'
    | '/journey/complete'
    | '/journey/confirm'
    | '/journey/milestone'
    | '/journey/orientation'
    | '/journey/preferences'
    | '/journey/privacy'
    | '/journey/reflection'
    | '/journey/review'
    | '/journey/safety'
    | '/journey/start'
    | '/pillars/$slug'
    | '/journey/quest/$questId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/appreciation'
    | '/book'
    | '/consent'
    | '/domains'
    | '/ecosystem'
    | '/foundation'
    | '/founder'
    | '/global'
    | '/join'
    | '/journey'
    | '/knowledge-before-action'
    | '/manifesto'
    | '/manifesto-full'
    | '/one-word-start'
    | '/pillars'
    | '/privacy'
    | '/soul'
    | '/status'
    | '/terms'
    | '/journey/accessibility'
    | '/journey/complete'
    | '/journey/confirm'
    | '/journey/milestone'
    | '/journey/orientation'
    | '/journey/preferences'
    | '/journey/privacy'
    | '/journey/reflection'
    | '/journey/review'
    | '/journey/safety'
    | '/journey/start'
    | '/pillars/$slug'
    | '/journey/quest/$questId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AppreciationRoute: typeof AppreciationRoute
  BookRoute: typeof BookRoute
  ConsentRoute: typeof ConsentRoute
  DomainsRoute: typeof DomainsRoute
  EcosystemRoute: typeof EcosystemRoute
  FoundationRoute: typeof FoundationRoute
  FounderRoute: typeof FounderRoute
  GlobalRoute: typeof GlobalRoute
  JoinRoute: typeof JoinRoute
  JourneyRoute: typeof JourneyRouteWithChildren
  KnowledgeBeforeActionRoute: typeof KnowledgeBeforeActionRoute
  ManifestoRoute: typeof ManifestoRoute
  ManifestoFullRoute: typeof ManifestoFullRoute
  OneWordStartRoute: typeof OneWordStartRoute
  PillarsRoute: typeof PillarsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SoulRoute: typeof SoulRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soul': {
      id: '/soul'
      path: '/soul'
      fullPath: '/soul'
      preLoaderRoute: typeof SoulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillars': {
      id: '/pillars'
      path: '/pillars'
      fullPath: '/pillars'
      preLoaderRoute: typeof PillarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one-word-start': {
      id: '/one-word-start'
      path: '/one-word-start'
      fullPath: '/one-word-start'
      preLoaderRoute: typeof OneWordStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto-full': {
      id: '/manifesto-full'
      path: '/manifesto-full'
      fullPath: '/manifesto-full'
      preLoaderRoute: typeof ManifestoFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-before-action': {
      id: '/knowledge-before-action'
      path: '/knowledge-before-action'
      fullPath: '/knowledge-before-action'
      preLoaderRoute: typeof KnowledgeBeforeActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global': {
      id: '/global'
      path: '/global'
      fullPath: '/global'
      preLoaderRoute: typeof GlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation': {
      id: '/foundation'
      path: '/foundation'
      fullPath: '/foundation'
      preLoaderRoute: typeof FoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appreciation': {
      id: '/appreciation'
      path: '/appreciation'
      fullPath: '/appreciation'
      preLoaderRoute: typeof AppreciationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillars/$slug': {
      id: '/pillars/$slug'
      path: '/$slug'
      fullPath: '/pillars/$slug'
      preLoaderRoute: typeof PillarsSlugRouteImport
      parentRoute: typeof PillarsRoute
    }
    '/journey/start': {
      id: '/journey/start'
      path: '/start'
      fullPath: '/journey/start'
      preLoaderRoute: typeof JourneyStartRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/safety': {
      id: '/journey/safety'
      path: '/safety'
      fullPath: '/journey/safety'
      preLoaderRoute: typeof JourneySafetyRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/review': {
      id: '/journey/review'
      path: '/review'
      fullPath: '/journey/review'
      preLoaderRoute: typeof JourneyReviewRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/reflection': {
      id: '/journey/reflection'
      path: '/reflection'
      fullPath: '/journey/reflection'
      preLoaderRoute: typeof JourneyReflectionRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/privacy': {
      id: '/journey/privacy'
      path: '/privacy'
      fullPath: '/journey/privacy'
      preLoaderRoute: typeof JourneyPrivacyRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/preferences': {
      id: '/journey/preferences'
      path: '/preferences'
      fullPath: '/journey/preferences'
      preLoaderRoute: typeof JourneyPreferencesRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/orientation': {
      id: '/journey/orientation'
      path: '/orientation'
      fullPath: '/journey/orientation'
      preLoaderRoute: typeof JourneyOrientationRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/milestone': {
      id: '/journey/milestone'
      path: '/milestone'
      fullPath: '/journey/milestone'
      preLoaderRoute: typeof JourneyMilestoneRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/confirm': {
      id: '/journey/confirm'
      path: '/confirm'
      fullPath: '/journey/confirm'
      preLoaderRoute: typeof JourneyConfirmRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/complete': {
      id: '/journey/complete'
      path: '/complete'
      fullPath: '/journey/complete'
      preLoaderRoute: typeof JourneyCompleteRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/accessibility': {
      id: '/journey/accessibility'
      path: '/accessibility'
      fullPath: '/journey/accessibility'
      preLoaderRoute: typeof JourneyAccessibilityRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/quest/$questId': {
      id: '/journey/quest/$questId'
      path: '/quest/$questId'
      fullPath: '/journey/quest/$questId'
      preLoaderRoute: typeof JourneyQuestQuestIdRouteImport
      parentRoute: typeof JourneyRoute
    }
  }
}

interface JourneyRouteChildren {
  JourneyAccessibilityRoute: typeof JourneyAccessibilityRoute
  JourneyCompleteRoute: typeof JourneyCompleteRoute
  JourneyConfirmRoute: typeof JourneyConfirmRoute
  JourneyMilestoneRoute: typeof JourneyMilestoneRoute
  JourneyOrientationRoute: typeof JourneyOrientationRoute
  JourneyPreferencesRoute: typeof JourneyPreferencesRoute
  JourneyPrivacyRoute: typeof JourneyPrivacyRoute
  JourneyReflectionRoute: typeof JourneyReflectionRoute
  JourneyReviewRoute: typeof JourneyReviewRoute
  JourneySafetyRoute: typeof JourneySafetyRoute
  JourneyStartRoute: typeof JourneyStartRoute
  JourneyQuestQuestIdRoute: typeof JourneyQuestQuestIdRoute
}

const JourneyRouteChildren: JourneyRouteChildren = {
  JourneyAccessibilityRoute: JourneyAccessibilityRoute,
  JourneyCompleteRoute: JourneyCompleteRoute,
  JourneyConfirmRoute: JourneyConfirmRoute,
  JourneyMilestoneRoute: JourneyMilestoneRoute,
  JourneyOrientationRoute: JourneyOrientationRoute,
  JourneyPreferencesRoute: JourneyPreferencesRoute,
  JourneyPrivacyRoute: JourneyPrivacyRoute,
  JourneyReflectionRoute: JourneyReflectionRoute,
  JourneyReviewRoute: JourneyReviewRoute,
  JourneySafetyRoute: JourneySafetyRoute,
  JourneyStartRoute: JourneyStartRoute,
  JourneyQuestQuestIdRoute: JourneyQuestQuestIdRoute,
}

const JourneyRouteWithChildren =
  JourneyRoute._addFileChildren(JourneyRouteChildren)

interface PillarsRouteChildren {
  PillarsSlugRoute: typeof PillarsSlugRoute
}

const PillarsRouteChildren: PillarsRouteChildren = {
  PillarsSlugRoute: PillarsSlugRoute,
}

const PillarsRouteWithChildren =
  PillarsRoute._addFileChildren(PillarsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AppreciationRoute: AppreciationRoute,
  BookRoute: BookRoute,
  ConsentRoute: ConsentRoute,
  DomainsRoute: DomainsRoute,
  EcosystemRoute: EcosystemRoute,
  FoundationRoute: FoundationRoute,
  FounderRoute: FounderRoute,
  GlobalRoute: GlobalRoute,
  JoinRoute: JoinRoute,
  JourneyRoute: JourneyRouteWithChildren,
  KnowledgeBeforeActionRoute: KnowledgeBeforeActionRoute,
  ManifestoRoute: ManifestoRoute,
  ManifestoFullRoute: ManifestoFullRoute,
  OneWordStartRoute: OneWordStartRoute,
  PillarsRoute: PillarsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SoulRoute: SoulRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
